<?php 
return array (
  'platform_open' => '1',
  'platform_weixin_open' => '1',
  'platform_weixin_mchid' => '1281572601',
  'platform_weixin_key' => 'a8d6a3d92f41fd9a8b5843f6c065d5fd',
  'platform_alipay_open' => '0',
  'platform_alipay_name' => '',
  'platform_alipay_pid' => '',
  'platform_alipay_key' => '',
  'platform_tenpay_open' => '0',
  'platform_tenpay_partnerid' => '',
  'platform_tenpay_partnerkey' => '',
  'platform_tenpayComputer_open' => '0',
  'platform_tenpayComputer_partnerid' => '',
  'platform_tenpayComputer_partnerkey' => '',
  'platform_allinpay_open' => '0',
  'platform_allinpay_merchantId' => '',
  'platform_allinpay_merchantKey' => '',
  'platform_yeepay_open' => '0',
  'platform_yeepay_merchantaccount' => '',
  'platform_yeepay_merchantPrivateKey' => '',
  'platform_yeepay_merchantPublicKey' => '',
  'platform_yeepay_yeepayPublicKey' => '',
  'platform_yeepay_product_catalog' => '',
);