window.onload=function(){
    $("#guanzhude-main").niceScroll({
        cursorcolor:"#7e8595",
        cursoropacitymax:1,
        touchbehavior:false,
        cursorwidth:"5px",
        cursorborder:"0",
        cursorborderradius:"4px"
    });
    $("#xinjing").niceScroll({
        cursorcolor:"#7e8595",
        cursoropacitymax:1,
        touchbehavior:false,
        cursorwidth:"5px",
        cursorborder:"0",
        cursorborderradius:"4px"
    });
}