<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  'ap_id' => '1053',
  'ap_name' => '商品2',
  'ap_intro' => '',
  'ap_class' => '0',
  'ap_display' => '2',
  'is_use' => '1',
  'ap_width' => '294',
  'ap_height' => '347',
  'ap_price' => '0',
  'adv_num' => '1',
  'click_num' => '0',
  'default_content' => '04995316712563944.jpg',
  'gc_id' => '0',
);