<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  'ap_id' => '1263',
  'ap_name' => '设计师banner1',
  'ap_intro' => '',
  'ap_class' => '0',
  'ap_display' => '2',
  'is_use' => '1',
  'ap_width' => '1200',
  'ap_height' => '300',
  'ap_price' => '0',
  'adv_num' => '1',
  'click_num' => '0',
  'default_content' => '',
  'gc_id' => '0',
  'adv_list' => 
  array (
    0 => 
    array (
      'adv_id' => '1095',
      'ap_id' => '1263',
      'adv_title' => '设计师',
      'adv_origin' => '',
      'adv_price' => '0',
      'adv_content' => 'a:2:{s:7:"adv_pic";s:21:"05076422841332218.jpg";s:11:"adv_pic_url";s:50:"www.site.com/index.php?act=store_list&amp;op=index";}',
      'adv_start_date' => '1449072000',
      'adv_end_date' => '1483113600',
      'slide_sort' => '0',
      'member_id' => '0',
      'member_name' => '',
      'click_num' => '0',
      'is_allow' => '1',
      'buy_style' => '',
      'goldpay' => '0',
      'gc_id' => '0',
      'store_id' => '0',
    ),
  ),
);