<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  'ap_id' => '1279',
  'ap_name' => '首页主广告图',
  'ap_intro' => '',
  'ap_class' => '0',
  'ap_display' => '2',
  'is_use' => '1',
  'ap_width' => '860',
  'ap_height' => '510',
  'ap_price' => '0',
  'adv_num' => '0',
  'click_num' => '0',
  'default_content' => '05198238779039820.jpg',
  'gc_id' => '0',
);