<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  1 => 
  array (
    'gc_id' => '1',
    'gc_name' => '女士用品',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '5',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      4 => 
      array (
        'gc_id' => '4',
        'gc_name' => '家居装饰',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1534 => 
          array (
            'gc_id' => '1534',
            'gc_name' => '测试',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1535 => 
          array (
            'gc_id' => '1535',
            'gc_name' => '测试2',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          13 => 
          array (
            'gc_id' => '13',
            'gc_name' => '灯光照明',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          14 => 
          array (
            'gc_id' => '14',
            'gc_name' => '装饰摆件',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          15 => 
          array (
            'gc_id' => '15',
            'gc_name' => '存钱罐',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          16 => 
          array (
            'gc_id' => '16',
            'gc_name' => '挂饰.风铃',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          17 => 
          array (
            'gc_id' => '17',
            'gc_name' => '花瓶.花插',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          18 => 
          array (
            'gc_id' => '18',
            'gc_name' => '香薰用品',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          19 => 
          array (
            'gc_id' => '19',
            'gc_name' => '绿植.盆栽',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          20 => 
          array (
            'gc_id' => '20',
            'gc_name' => '像框.相架',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          21 => 
          array (
            'gc_id' => '21',
            'gc_name' => '墙纸.贴饰',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          22 => 
          array (
            'gc_id' => '22',
            'gc_name' => '音乐盒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          24 => 
          array (
            'gc_id' => '24',
            'gc_name' => '香味蜡烛',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '4',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      6 => 
      array (
        'gc_id' => '6',
        'gc_name' => '家具清洁',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          59 => 
          array (
            'gc_id' => '59',
            'gc_name' => '电器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '6',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          60 => 
          array (
            'gc_id' => '60',
            'gc_name' => '厨房用具',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '6',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          61 => 
          array (
            'gc_id' => '61',
            'gc_name' => '清洁/收纳',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '6',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          62 => 
          array (
            'gc_id' => '62',
            'gc_name' => '餐具/酒具',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '6',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          63 => 
          array (
            'gc_id' => '63',
            'gc_name' => '保鲜容器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '6',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      8 => 
      array (
        'gc_id' => '8',
        'gc_name' => '家居收纳',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1329 => 
          array (
            'gc_id' => '1329',
            'gc_name' => '挂钩',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '8',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          90 => 
          array (
            'gc_id' => '90',
            'gc_name' => '收纳盒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '8',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          92 => 
          array (
            'gc_id' => '92',
            'gc_name' => '储物柜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '8',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          94 => 
          array (
            'gc_id' => '94',
            'gc_name' => '收纳袋',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '8',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      9 => 
      array (
        'gc_id' => '9',
        'gc_name' => '床上用品',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          107 => 
          array (
            'gc_id' => '107',
            'gc_name' => '毛毯/珊瑚绒毯',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '9',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          108 => 
          array (
            'gc_id' => '108',
            'gc_name' => '抱枕/坐垫',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '9',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          109 => 
          array (
            'gc_id' => '109',
            'gc_name' => '枕头/保健枕',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '9',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          112 => 
          array (
            'gc_id' => '112',
            'gc_name' => '夏日凉席',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '9',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          113 => 
          array (
            'gc_id' => '113',
            'gc_name' => '床品套装/四件套',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '9',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      11 => 
      array (
        'gc_id' => '11',
        'gc_name' => '生活杂货',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-1.jpg',
    'class3' => 
    array (
      1534 => 
      array (
        'gc_id' => '1534',
        'gc_name' => '测试',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '4',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1535 => 
      array (
        'gc_id' => '1535',
        'gc_name' => '测试2',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '4',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1329 => 
      array (
        'gc_id' => '1329',
        'gc_name' => '挂钩',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '8',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      13 => 
      array (
        'gc_id' => '13',
        'gc_name' => '灯光照明',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '4',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      14 => 
      array (
        'gc_id' => '14',
        'gc_name' => '装饰摆件',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '4',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  256 => 
  array (
    'gc_id' => '256',
    'gc_name' => '男士用品',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '8',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1171 => 
      array (
        'gc_id' => '1171',
        'gc_name' => '游戏玩具',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '256',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1175 => 
          array (
            'gc_id' => '1175',
            'gc_name' => '益智',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1171',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1176 => 
          array (
            'gc_id' => '1176',
            'gc_name' => '棋牌',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1171',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1177 => 
          array (
            'gc_id' => '1177',
            'gc_name' => '桌游',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1171',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1173 => 
      array (
        'gc_id' => '1173',
        'gc_name' => '洗护清洁',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '256',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1174 => 
      array (
        'gc_id' => '1174',
        'gc_name' => '安全出行',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '256',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1225 => 
      array (
        'gc_id' => '1225',
        'gc_name' => '喂养用品',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '256',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-256.jpg',
    'class3' => 
    array (
      1175 => 
      array (
        'gc_id' => '1175',
        'gc_name' => '益智',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1171',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1176 => 
      array (
        'gc_id' => '1176',
        'gc_name' => '棋牌',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1171',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1177 => 
      array (
        'gc_id' => '1177',
        'gc_name' => '桌游',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1171',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  308 => 
  array (
    'gc_id' => '308',
    'gc_name' => '我爱我家',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '8',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1086 => 
      array (
        'gc_id' => '1086',
        'gc_name' => '户外装备',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1131 => 
          array (
            'gc_id' => '1131',
            'gc_name' => '户外工具',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1132 => 
          array (
            'gc_id' => '1132',
            'gc_name' => '救生用品',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1133 => 
          array (
            'gc_id' => '1133',
            'gc_name' => '帐篷/垫子',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1134 => 
          array (
            'gc_id' => '1134',
            'gc_name' => '户外仪表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1135 => 
          array (
            'gc_id' => '1135',
            'gc_name' => '睡袋/吊床',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1140 => 
          array (
            'gc_id' => '1140',
            'gc_name' => '户外照明',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1086',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1098 => 
      array (
        'gc_id' => '1098',
        'gc_name' => '出行箱包',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1099 => 
          array (
            'gc_id' => '1099',
            'gc_name' => '收纳包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1098',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1101 => 
          array (
            'gc_id' => '1101',
            'gc_name' => '背包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1098',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1138 => 
      array (
        'gc_id' => '1138',
        'gc_name' => '运动健身',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1246 => 
          array (
            'gc_id' => '1246',
            'gc_name' => '雨伞',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1138',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1247 => 
          array (
            'gc_id' => '1247',
            'gc_name' => '雨衣',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1138',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1311 => 
      array (
        'gc_id' => '1311',
        'gc_name' => '车载装备',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1312 => 
          array (
            'gc_id' => '1312',
            'gc_name' => '车载香薰',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1313 => 
          array (
            'gc_id' => '1313',
            'gc_name' => '车载支架',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1314 => 
          array (
            'gc_id' => '1314',
            'gc_name' => '车载充电器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1315 => 
          array (
            'gc_id' => '1315',
            'gc_name' => '车载手机座',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1317 => 
          array (
            'gc_id' => '1317',
            'gc_name' => '挂件',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1502 => 
          array (
            'gc_id' => '1502',
            'gc_name' => '汽车头枕',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1311',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      312 => 
      array (
        'gc_id' => '312',
        'gc_name' => '户外收纳',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          358 => 
          array (
            'gc_id' => '358',
            'gc_name' => '纸巾盒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '312',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      313 => 
      array (
        'gc_id' => '313',
        'gc_name' => '运动户外',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '308',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1097 => 
          array (
            'gc_id' => '1097',
            'gc_name' => '跳绳',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '313',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1251 => 
          array (
            'gc_id' => '1251',
            'gc_name' => '折叠车/平衡车',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '313',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          373 => 
          array (
            'gc_id' => '373',
            'gc_name' => '四轮滑板',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '313',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          374 => 
          array (
            'gc_id' => '374',
            'gc_name' => '握力球',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '313',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          375 => 
          array (
            'gc_id' => '375',
            'gc_name' => '山地车/公路车',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '313',
            'commis_rate' => '5',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-308.jpg',
    'class3' => 
    array (
      1097 => 
      array (
        'gc_id' => '1097',
        'gc_name' => '跳绳',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '313',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1251 => 
      array (
        'gc_id' => '1251',
        'gc_name' => '折叠车/平衡车',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '313',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1131 => 
      array (
        'gc_id' => '1131',
        'gc_name' => '户外工具',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1086',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1132 => 
      array (
        'gc_id' => '1132',
        'gc_name' => '救生用品',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1086',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1133 => 
      array (
        'gc_id' => '1133',
        'gc_name' => '帐篷/垫子',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1086',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  470 => 
  array (
    'gc_id' => '470',
    'gc_name' => '科技数码',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '8',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1085 => 
      array (
        'gc_id' => '1085',
        'gc_name' => '数码摄影',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '470',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1126 => 
          array (
            'gc_id' => '1126',
            'gc_name' => '拍照·摄影',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1085',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1128 => 
          array (
            'gc_id' => '1128',
            'gc_name' => '手柄·摇杆',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1085',
            'commis_rate' => '8',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1184 => 
      array (
        'gc_id' => '1184',
        'gc_name' => '数码电玩',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '470',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1255 => 
          array (
            'gc_id' => '1255',
            'gc_name' => '电动/遥控飞机',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1257 => 
          array (
            'gc_id' => '1257',
            'gc_name' => '电动/遥控车',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1258 => 
          array (
            'gc_id' => '1258',
            'gc_name' => '智能无人机',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1324 => 
          array (
            'gc_id' => '1324',
            'gc_name' => '智能吉他',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1431 => 
          array (
            'gc_id' => '1431',
            'gc_name' => '互动机器人',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1514 => 
          array (
            'gc_id' => '1514',
            'gc_name' => '水上飞行器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1522 => 
          array (
            'gc_id' => '1522',
            'gc_name' => '扫描仪',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1184',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1273 => 
      array (
        'gc_id' => '1273',
        'gc_name' => '智能家居',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '470',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1503 => 
          array (
            'gc_id' => '1503',
            'gc_name' => '信号放大器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1273',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1510 => 
          array (
            'gc_id' => '1510',
            'gc_name' => '娱乐机器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1273',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1511 => 
          array (
            'gc_id' => '1511',
            'gc_name' => '便携式洗衣机',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1273',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1513 => 
          array (
            'gc_id' => '1513',
            'gc_name' => '智能家居用品',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1273',
            'commis_rate' => '5',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1524 => 
      array (
        'gc_id' => '1524',
        'gc_name' => '智能穿戴',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '470',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1075 => 
      array (
        'gc_id' => '1075',
        'gc_name' => '数码配件',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '470',
        'commis_rate' => '8',
        'gc_sort' => '1',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-470.jpg',
    'class3' => 
    array (
      1126 => 
      array (
        'gc_id' => '1126',
        'gc_name' => '拍照·摄影',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1085',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1128 => 
      array (
        'gc_id' => '1128',
        'gc_name' => '手柄·摇杆',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1085',
        'commis_rate' => '8',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1255 => 
      array (
        'gc_id' => '1255',
        'gc_name' => '电动/遥控飞机',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1184',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1257 => 
      array (
        'gc_id' => '1257',
        'gc_name' => '电动/遥控车',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1184',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1258 => 
      array (
        'gc_id' => '1258',
        'gc_name' => '智能无人机',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1184',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  593 => 
  array (
    'gc_id' => '593',
    'gc_name' => '艺术生活',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '6',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1061 => 
      array (
        'gc_id' => '1061',
        'gc_name' => '数码办公',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '593',
        'commis_rate' => '6',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1536 => 
      array (
        'gc_id' => '1536',
        'gc_name' => '绘画',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '593',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      594 => 
      array (
        'gc_id' => '594',
        'gc_name' => '文具用品',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '593',
        'commis_rate' => '3',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1288 => 
          array (
            'gc_id' => '1288',
            'gc_name' => '计算器',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1333 => 
          array (
            'gc_id' => '1333',
            'gc_name' => '本册/便签',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1418 => 
          array (
            'gc_id' => '1418',
            'gc_name' => '蜡笔',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1429 => 
          array (
            'gc_id' => '1429',
            'gc_name' => '笔筒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1500 => 
          array (
            'gc_id' => '1500',
            'gc_name' => '笔',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          604 => 
          array (
            'gc_id' => '604',
            'gc_name' => '硒鼓/墨粉',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          605 => 
          array (
            'gc_id' => '605',
            'gc_name' => '墨盒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          606 => 
          array (
            'gc_id' => '606',
            'gc_name' => '色带',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          607 => 
          array (
            'gc_id' => '607',
            'gc_name' => '纸类',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          608 => 
          array (
            'gc_id' => '608',
            'gc_name' => '文件管理',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '594',
            'commis_rate' => '3',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      596 => 
      array (
        'gc_id' => '596',
        'gc_name' => '办公设备',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '593',
        'commis_rate' => '6',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      597 => 
      array (
        'gc_id' => '597',
        'gc_name' => '办公收纳',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '593',
        'commis_rate' => '6',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          622 => 
          array (
            'gc_id' => '622',
            'gc_name' => '卡套卡包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '597',
            'commis_rate' => '6',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          623 => 
          array (
            'gc_id' => '623',
            'gc_name' => '笔袋',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '597',
            'commis_rate' => '6',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          624 => 
          array (
            'gc_id' => '624',
            'gc_name' => '收纳盒',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '597',
            'commis_rate' => '6',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          625 => 
          array (
            'gc_id' => '625',
            'gc_name' => '收纳柜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '597',
            'commis_rate' => '6',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          626 => 
          array (
            'gc_id' => '626',
            'gc_name' => '文件架',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '597',
            'commis_rate' => '6',
            'gc_sort' => '255',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-593.jpg',
    'class3' => 
    array (
      1288 => 
      array (
        'gc_id' => '1288',
        'gc_name' => '计算器',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '594',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1333 => 
      array (
        'gc_id' => '1333',
        'gc_name' => '本册/便签',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '594',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1418 => 
      array (
        'gc_id' => '1418',
        'gc_name' => '蜡笔',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '594',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1429 => 
      array (
        'gc_id' => '1429',
        'gc_name' => '笔筒',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '594',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1500 => 
      array (
        'gc_id' => '1500',
        'gc_name' => '笔',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '594',
        'commis_rate' => '3',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  662 => 
  array (
    'gc_id' => '662',
    'gc_name' => '美味餐厨',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '5',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1149 => 
      array (
        'gc_id' => '1149',
        'gc_name' => '口腔护理',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '662',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1154 => 
      array (
        'gc_id' => '1154',
        'gc_name' => '全身护理',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '662',
        'commis_rate' => '5',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      664 => 
      array (
        'gc_id' => '664',
        'gc_name' => '面部护肤',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '662',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      668 => 
      array (
        'gc_id' => '668',
        'gc_name' => '特殊护理',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '662',
        'commis_rate' => '5',
        'gc_sort' => '255',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-662.jpg',
  ),
  1058 => 
  array (
    'gc_id' => '1058',
    'gc_name' => '欢乐办公',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '10',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1094 => 
      array (
        'gc_id' => '1094',
        'gc_name' => '挂饰',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1334 => 
          array (
            'gc_id' => '1334',
            'gc_name' => '挂件',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1094',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1335 => 
          array (
            'gc_id' => '1335',
            'gc_name' => '小摆件',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1094',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1336 => 
          array (
            'gc_id' => '1336',
            'gc_name' => '小玩偶',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1094',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1406 => 
          array (
            'gc_id' => '1406',
            'gc_name' => '钥匙扣',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1094',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1107 => 
      array (
        'gc_id' => '1107',
        'gc_name' => '女包',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1337 => 
          array (
            'gc_id' => '1337',
            'gc_name' => '单肩包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1338 => 
          array (
            'gc_id' => '1338',
            'gc_name' => '真皮包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1339 => 
          array (
            'gc_id' => '1339',
            'gc_name' => '手提包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1340 => 
          array (
            'gc_id' => '1340',
            'gc_name' => '双肩包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1341 => 
          array (
            'gc_id' => '1341',
            'gc_name' => '斜挎包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1342 => 
          array (
            'gc_id' => '1342',
            'gc_name' => '手拿包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1343 => 
          array (
            'gc_id' => '1343',
            'gc_name' => '复古包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1107',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1108 => 
      array (
        'gc_id' => '1108',
        'gc_name' => '钱包',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1344 => 
          array (
            'gc_id' => '1344',
            'gc_name' => '长款',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1108',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1345 => 
          array (
            'gc_id' => '1345',
            'gc_name' => '短款',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1108',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1417 => 
          array (
            'gc_id' => '1417',
            'gc_name' => '中款',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1108',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1434 => 
          array (
            'gc_id' => '1434',
            'gc_name' => '零钱包',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1108',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1109 => 
      array (
        'gc_id' => '1109',
        'gc_name' => '项链',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1346 => 
          array (
            'gc_id' => '1346',
            'gc_name' => '吊饰',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1109',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1347 => 
          array (
            'gc_id' => '1347',
            'gc_name' => '长款',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1109',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1416 => 
          array (
            'gc_id' => '1416',
            'gc_name' => '合金/镀银/镀金',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1109',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1113 => 
      array (
        'gc_id' => '1113',
        'gc_name' => '口罩.眼罩',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1349 => 
          array (
            'gc_id' => '1349',
            'gc_name' => '防尘',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1113',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1392 => 
          array (
            'gc_id' => '1392',
            'gc_name' => '冰敷',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1113',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1420 => 
          array (
            'gc_id' => '1420',
            'gc_name' => '遮光',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1113',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1114 => 
      array (
        'gc_id' => '1114',
        'gc_name' => '围巾',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1350 => 
          array (
            'gc_id' => '1350',
            'gc_name' => '长方形',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1114',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1351 => 
          array (
            'gc_id' => '1351',
            'gc_name' => '方巾',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1114',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1115 => 
      array (
        'gc_id' => '1115',
        'gc_name' => '眼镜',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1352 => 
          array (
            'gc_id' => '1352',
            'gc_name' => '太阳眼镜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1115',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1353 => 
          array (
            'gc_id' => '1353',
            'gc_name' => '防幅射眼镜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1115',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1354 => 
          array (
            'gc_id' => '1354',
            'gc_name' => '3D眼镜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1115',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1355 => 
          array (
            'gc_id' => '1355',
            'gc_name' => '装饰眼镜',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1115',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1116 => 
      array (
        'gc_id' => '1116',
        'gc_name' => '腰带',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1359 => 
          array (
            'gc_id' => '1359',
            'gc_name' => '日韩风',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1116',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1360 => 
          array (
            'gc_id' => '1360',
            'gc_name' => '百搭',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1116',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1361 => 
          array (
            'gc_id' => '1361',
            'gc_name' => '帆布',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1116',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1185 => 
      array (
        'gc_id' => '1185',
        'gc_name' => '手套',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1365 => 
          array (
            'gc_id' => '1365',
            'gc_name' => '防风',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1185',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1366 => 
          array (
            'gc_id' => '1366',
            'gc_name' => '触屏',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1185',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1367 => 
          array (
            'gc_id' => '1367',
            'gc_name' => '防水',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1185',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1186 => 
      array (
        'gc_id' => '1186',
        'gc_name' => '手链',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1368 => 
          array (
            'gc_id' => '1368',
            'gc_name' => '创新',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1186',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1369 => 
          array (
            'gc_id' => '1369',
            'gc_name' => '纯银',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1186',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1370 => 
          array (
            'gc_id' => '1370',
            'gc_name' => '镶嵌',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1186',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1415 => 
          array (
            'gc_id' => '1415',
            'gc_name' => '串珠',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1186',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1187 => 
      array (
        'gc_id' => '1187',
        'gc_name' => '戒指',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1371 => 
          array (
            'gc_id' => '1371',
            'gc_name' => '男款',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1372 => 
          array (
            'gc_id' => '1372',
            'gc_name' => '欧式',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1373 => 
          array (
            'gc_id' => '1373',
            'gc_name' => '宝石镶嵌',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1410 => 
          array (
            'gc_id' => '1410',
            'gc_name' => '简约',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1411 => 
          array (
            'gc_id' => '1411',
            'gc_name' => '纯银',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1412 => 
          array (
            'gc_id' => '1412',
            'gc_name' => '合金/镀银/镀金',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1413 => 
          array (
            'gc_id' => '1413',
            'gc_name' => '锆石/水钻',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1414 => 
          array (
            'gc_id' => '1414',
            'gc_name' => '水晶',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1187',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1515 => 
      array (
        'gc_id' => '1515',
        'gc_name' => '手表',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1058',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1516 => 
          array (
            'gc_id' => '1516',
            'gc_name' => '石英表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1517 => 
          array (
            'gc_id' => '1517',
            'gc_name' => '电子表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1518 => 
          array (
            'gc_id' => '1518',
            'gc_name' => '机械表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1519 => 
          array (
            'gc_id' => '1519',
            'gc_name' => '光能表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1520 => 
          array (
            'gc_id' => '1520',
            'gc_name' => '智能表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1521 => 
          array (
            'gc_id' => '1521',
            'gc_name' => '太阳能表',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1515',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-1058.jpg',
    'class3' => 
    array (
      1334 => 
      array (
        'gc_id' => '1334',
        'gc_name' => '挂件',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1094',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1335 => 
      array (
        'gc_id' => '1335',
        'gc_name' => '小摆件',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1094',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1336 => 
      array (
        'gc_id' => '1336',
        'gc_name' => '小玩偶',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1094',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1406 => 
      array (
        'gc_id' => '1406',
        'gc_name' => '钥匙扣',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1094',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1337 => 
      array (
        'gc_id' => '1337',
        'gc_name' => '单肩包',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1107',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
  1526 => 
  array (
    'gc_id' => '1526',
    'gc_name' => '旅行必备',
    'type_id' => '38',
    'type_name' => '颜色（主）',
    'gc_parent_id' => '0',
    'commis_rate' => '10',
    'gc_sort' => '255',
    'gc_virtual' => '0',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'class2' => 
    array (
      1527 => 
      array (
        'gc_id' => '1527',
        'gc_name' => '日常用品',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1526',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'class3' => 
        array (
          1531 => 
          array (
            'gc_id' => '1531',
            'gc_name' => '餐具',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1527',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1532 => 
          array (
            'gc_id' => '1532',
            'gc_name' => '居家',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1527',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
          1533 => 
          array (
            'gc_id' => '1533',
            'gc_name' => '美容',
            'type_id' => '38',
            'type_name' => '颜色（主）',
            'gc_parent_id' => '1527',
            'commis_rate' => '10',
            'gc_sort' => '0',
            'gc_virtual' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
          ),
        ),
        'brands' => NULL,
      ),
      1528 => 
      array (
        'gc_id' => '1528',
        'gc_name' => '旅行小物',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1526',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1529 => 
      array (
        'gc_id' => '1529',
        'gc_name' => '主粮零食',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1526',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
      1530 => 
      array (
        'gc_id' => '1530',
        'gc_name' => '旅游装备',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1526',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'brands' => NULL,
      ),
    ),
    'pic' => 'http://www.site.com/data/upload/shop/common/category-pic-1526.jpg',
    'class3' => 
    array (
      1531 => 
      array (
        'gc_id' => '1531',
        'gc_name' => '餐具',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1527',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1532 => 
      array (
        'gc_id' => '1532',
        'gc_name' => '居家',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1527',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
      1533 => 
      array (
        'gc_id' => '1533',
        'gc_name' => '美容',
        'type_id' => '38',
        'type_name' => '颜色（主）',
        'gc_parent_id' => '1527',
        'commis_rate' => '10',
        'gc_sort' => '0',
        'gc_virtual' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
      ),
    ),
  ),
);