<?php defined('InShopNC') or exit('Access Invalid!'); return array (
  'ap_id' => '1260',
  'ap_name' => '幻灯片3',
  'ap_intro' => '',
  'ap_class' => '0',
  'ap_display' => '2',
  'is_use' => '1',
  'ap_width' => '1200',
  'ap_height' => '450',
  'ap_price' => '0',
  'adv_num' => '1',
  'click_num' => '0',
  'default_content' => '05127361645009564.jpg',
  'gc_id' => '0',
  'adv_list' => 
  array (
    0 => 
    array (
      'adv_id' => '1085',
      'ap_id' => '1260',
      'adv_title' => '3',
      'adv_origin' => '',
      'adv_price' => '0',
      'adv_content' => 'a:2:{s:7:"adv_pic";s:21:"05143118865089946.jpg";s:11:"adv_pic_url";s:51:"www.site.com/index.php?act=specialy&amp;op=qingming";}',
      'adv_start_date' => '1448380800',
      'adv_end_date' => '1605110400',
      'slide_sort' => '0',
      'member_id' => '0',
      'member_name' => '',
      'click_num' => '0',
      'is_allow' => '1',
      'buy_style' => '',
      'goldpay' => '0',
      'gc_id' => '0',
      'store_id' => '0',
    ),
  ),
);